using './main.bicep'

param location = 'westeurope'
param tags = {
  environment: 'development'
  issue: '34'
  project: 'jazz'
  purpose: 'windows-qualification'
  managedBy: 'bicep'
}
param keyVaultName = 'kvjazzwin96fd974a'
param developmentBreakGlassCredentialName = 'windows-development-local-admin-password'
param qualificationBreakGlassCredentialName = 'windows-qualification-local-admin-password'
param virtualNetworkName = 'vnet-jazz-windows-test-weu'
param virtualNetworkPrefix = '10.42.0.0/24'
param bastionSubnetPrefix = '10.42.0.0/26'
param developmentSubnetName = 'snet-jazz-development'
param developmentSubnetPrefix = '10.42.0.64/26'
param qualificationSubnetName = 'snet-jazz-qualification'
param qualificationSubnetPrefix = '10.42.0.128/26'
param developmentNetworkSecurityGroupName = 'nsg-jazz-development'
param qualificationNetworkSecurityGroupName = 'nsg-jazz-qualification'
param developmentNicName = 'nic-jazz-win-dev'
param qualificationNicName = 'nic-jazz-win-qualification'
param bastionName = 'bas-jazz-windows-test-weu'
param bastionPublicIpName = 'pip-jazz-bastion-weu'
param bastionSku = 'Basic'
param natGatewayName = 'ng-jazz-windows-test-weu'
param natGatewayPublicIpName = 'pip-jazz-egress-weu'
param natGatewayIdleTimeoutMinutes = 10
param rdpPort = '3389'
param allowBastionRdpPriority = 100
param denyLateralTrafficPriority = 110
param developmentVmName = 'jazz-win-dev'
param developmentVmSize = 'Standard_D4as_v5'
param qualificationVmName = 'jazz-win-qual'
param qualificationVmSize = 'Standard_D2as_v5'
param adminUsername = 'jazzbreakglass'
param imagePublisher = 'MicrosoftWindowsDesktop'
param imageOffer = 'windows-11'
param imageSku = 'win11-25h2-ent'
param imageVersion = '26200.9168.260809'
param osDiskSizeGiB = 128
param osDiskStorageAccountType = 'Premium_LRS'
param windowsTimeZone = 'Central Europe Standard Time'
param operatorObjectId = 'b9977d7c-2374-4e13-a35f-c761d56abb76'
param vmAdministratorLoginRoleDefinitionId = '1c0163c0-47e6-4577-8991-ea5c82e286e4'
param readerRoleDefinitionId = 'acdd72a7-3385-48ef-bd42-f606fba81ae7'
